markdown: kramdown 
permalink: /:year/:month/:title
title: Linyi's blog
url: http://www.linyi.press
subscribe: http://www.linyi.press/feed
exclude: [ README.md, newpost.rb ]
domain: www.linyi.press
author: linyi
email: peter.linyi159@gmail.com
duoshuoShortname: nomath
safe: true
